### ISSUE TITLE
Identify the next schemas to add

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc-schemas#12]
Identify the next schemas to add based on the current version of the MIAC schemas.

@vpchung Are the schemas that you already added, for example `Challenge` and `Grant`, follow closely the MIAC schemas? My assumption is that the MIAC schema is still "fluid" and that we can use our work in this repo to improve it. Do you agree?

**Comment by vpchung** [comment]
@tschaffter to a certain extent, the current schemas do follow the MIAC schema. And yes, the MIAC schema is very much a work in progress! 

I am going to hold off on adding additional schemas until after the current API inspections and testings.

**Comment by tschaffter** [comment]
> I am going to hold off on adding additional schemas until after the current API inspections and testings.

Who is conducting this inspection and testing?

**Comment by vpchung** [comment]
I'm testing them.

**Comment by tschaffter** [comment]
On the note of testing, I implemented last week integration tests for the NLP Sandbox Data Node project, the API service that uses MongoDB and used to seed the ROCC API service. When we get there this work can directly be transposed to create the integration tests of the ROCC portal!

**Comment by tschaffter** [comment]
https://github.com/nlpsandbox/data-node/pull/97

**Comment by tschaffter** [comment]
This ticket is too generic. Also we are now starting to add more schema naturally.
