### ISSUE TITLE
Update User schemas

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc-schemas#120]
### Specification

- User should extends `Person`
- `User.id` could be an ObjectId, maybe something shorter later (Twitter `User.id` example: `2244994945`)
- `User.username`
- Decide between `Person.name` or (`Person.firstName`, `Person.lastName`)
- `User.description`
- `User.verified`
- `User.profileImageUrl`
- `User.errors` (see [Twitter doc](https://developer.twitter.com/en/docs/twitter-api/users/lookup/api-reference/get-users-id)), maybe add this property later

### References

- [Twitter user API](https://developer.twitter.com/en/docs/twitter-api/users/lookup/api-reference/get-users-id)

**Comment by vpchung** [comment]
I previously configured the User schema to use the `username` for lookup.  Based on the Twitter API, should we reconfigure it to use an ID instead? Maybe both?

Currently, the User object is:

- `username`
- `role`
- `Person.firstName`
- `Person.lastName`
- `Person.email`
- `Person.organizations`

With the specs above, the User object will become:

- `id`
- `username`
- `Person.firstName`
- `Person.lastName`
- `Person.email`
- `Person.organizations`
- `description`
- `verified`
- `profileImageUrl`

I don't know if an `errors` property will be needed, as we are handling that within the path, e.g.

```
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: ../components/schemas/EmptyObject.yaml
    '400':
      $ref: ../components/responses/NotFound.yaml
    '500':
      $ref: ../components/responses/InternalServerError.yaml
```

**Comment by tschaffter** [comment]
@vpchung Looks good to me. I guess Twitter is using `User.errors` to save recent errors a user experienced. They may use this information to provide user support. For now let's not include this property.

**Comment by tschaffter** [comment]
@vpchung The new User schemas adds several of the properties listed in this ticket. The only one left out temporarily are `verified` and `organizations`.
