### ISSUE TITLE
Review Person schema

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc-schemas#30]
The property `Person.personId` is currently a random ID generated by MongoDB.

I was considering making `Person.email` the primary ID of Person, however this would entail that all challenge platform can provide "automatically" an email for the organizers of a challenge. Considering that the organizers of challenges are usually "users" of the challenge platform with a complete account, this seems plausible.

## Pros of using email as primary of of `Person`

- Reduce the number of `Person` objects in the DB, which leads to better performance

## Cons

- We may not have the email of all past DREAM challenge organizers

**Comment by tschaffter** [comment]
@vpchung Have you collected email addresses for the Persons from past DREAM challenges?

**Comment by vpchung** [comment]
I have not... but I can do it if needed. It looks like `synapseclient` has a `getUserProfile()` I could take advantage of:

```
>>> syn.getUserProfile("Verena Chung").get('emails')
['verena.chung@sagebase.org']
```

**Comment by vpchung** [comment]
On second thought, the above tactic may not work. I just tried with a couple names (who I know have accounts on Synapse), and they either don't have the `emails` item pair or there are no returned results at all.

**Comment by tschaffter** [comment]
> The only potential issue is that there might be more than one email per person (so we'll have to choose one -- which could then run into the issue of not properly linking Person to the correct User) or the email might not be updated.

I see.. (https://rest-docs.synapse.org/rest/GET/userProfile.html). If only we could get access to the primary email address, but that's something that Synapse is protecting. So we need to keep the dedicated `Person.personId`.

**Comment by tschaffter** [comment]
In the future and in production release, we could automatically send an email to Person objects that have an email address to invite them to create a User account on the registry.

At some point we may then have `Challenge.organizers` that looks something like that:
description: Challenge object
properties:
   organizers:
      oneOf:
         - $ref: Person.yaml
         - $ref: User.yaml

**Comment by tschaffter** [comment]
We've got the `Person` schema nailed down.
