### ISSUE TITLE
Add `count` or `totalCount` to paginated responses

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/rocc-schemas#37]
So one could easily see the total count of results when using the `list_*` APIs

**Comment by tschaffter** [comment]
An alternative approach could be to use a HEAD request to get a header property like `X-Result-Count` or `X-Result-Total` or both. There does not seem to be a standard for the names of these properties. The advantage of the HEAD approach that we can get the size of the collection before starting to pull the data.

**Comment by tschaffter** [comment]
See also:

- https://portal.whereversim.com/api/doc/collections.html
- Google uses properties like `totalItems` or `totalResults` (see [this example](https://developers.google.com/blogger/docs/3.0/reference/blogs#resource))

**Comment by tschaffter** [comment]
@vpchung I recommending adding the property `totalResults: <integer>`. YouTube API makes use of this approach (see [example](https://developers.google.com/youtube/v3/docs/search/list#response)).
