### ISSUE TITLE
Consider returning only the ID of entity created

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc-schemas#43]
When executing a POST request, we are returning the full object, which is often the same data as given as input + the ID of the entity created.

The first observation is that we are currently returning information to the user that he/she already has. The POST request would complete faster if we were returning only the information delta (typically the ID of the entity created). This is particularly true for potentially large object posted (e.g. clinical note in the NLP Sandbox Data Node). From a performance perspective, it would make sense to return only the ID of the entity.

In December, I started to create "schema" for properties such as `TagId.yaml`, `ChallengeId.yaml`, etc. The motivation is that these properties can be used as well in a schema like `Challenge.yaml` using `$ref: ChallengeId.yaml` as well as in path and query properties, for example:

```
parameters:
  - in: path
    name: tagId
    description: The ID of the tag
    required: true
    schema:
      $ref: ../components/schemas/TagId.yaml
get:
  tags:
    - Tag
  summary: Get a tag
  description: Returns the tag specified
  operationId: getTag
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Tag.yaml
    '403':
      $ref: ../components/responses/Unauthorized.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
```

So far this is just to say that we could return the ID schema like `ChallengeId` instead of the full `Challenge` object.

@thomasyu888 @vpchung Thoughts?

**Comment by vpchung** [comment]
Returning just the ID is preferable to me.

**Comment by tschaffter** [comment]
Should we return 201 instead of our current 200? We should refer to the [IETF standard for 201](https://tools.ietf.org/html/rfc7231#section-6.3.2).

>    The 201 (Created) status code indicates that the request has been
   fulfilled and has resulted in one or more new resources being
   created.  The primary resource created by the request is identified
   by either a Location header field in the response or, if no Location
   field is received, by the effective request URI.

The new implementation would technically not comply with `The primary resource created by the request is identified
   by either a Location header field in the response or, if no Location field is received, by the effective request URI.`

But then the doc says:

> The 201 response payload typically describes and links to the
   resource(s) created.  See Section 7.2 for a discussion of the meaning
   and purpose of validator header fields, such as ETag and
   Last-Modified, in a 201 response.

The sentence `The 201 response payload typically describes and links to the resource(s) created.` seems to open us the door to be compliant with 201, as the ID that we return in the `payload` can be used to "link" the returned payload content with the created entity.

I propose to adopted `201 Created` for POST requests that create objects in the DB.

**Comment by thomasyu888** [comment]
Although, in our discussion for using `200` vs `204`, we decided to use `200` to keep the status codes uniform - i think it does make sense to use `201` here.   

Are you referring to this link feature: https://swagger.io/docs/specification/links/

**Comment by tschaffter** [comment]
> Are you referring to this link feature: https://swagger.io/docs/specification/links/

Thanks for sharing this resource! `links` seems to be for documentation purposes. I'll open a separate ticket to explore this improvement as well as another one to investigate pagination via cursors mentioned on the page you shared.
