### ISSUE TITLE
Resolve the readOnly dilemna

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc-schemas#44]
## Background

In order to adhere to the DRY (Don't repeat yourself) principle, we have defined a single schema, for example `Challenge.yaml`, that we used for the body of a POST request and the response body. However, in the cases where the ID of the newly created entity is generated by the DB, the user is not expected to provide a value for this field as part of the body of the POST request.

OpenAPI provides the options `readOnly: <boolean>` and `writeOnly: <boolean>` that are meant to be used with object properties that should be provided only as input or output. These two options are well supported by the Node package `@redocly/openapi-cli` that we use to generate an HTML visualization of the schemas. However, the options `readOnly` and `writeOnly` not perfectly supported by the `openapi-generator`, depending the programming language select for the generated server/client codebase. In the case of `python-flask` server, the issue is that the *schema examples* (automatically?) created seem to ignore the options `readOnly` and `writeOnly`. Therefore we heading to the web page `/api/v1/ui` to try a request, the body of a POST request may include an ID. The request is then rejected because the current implementation of the python-flask throws an an error when receiving values for parameters that are marked as `readOnly: true` (the same error probably affect `writeOnly`). I don't have the link handy, but previous searches online revealed that the server should ignore values for properties marked as `readOnly` instead of throwing errors. A workaround may be for us to provide full schema example instead of example for individual properties that are then used by the generator to created a full example, see the section [External Example](https://swagger.io/docs/specification/adding-examples/).

Another issue is that we have started to define properties in their own file, like `TagId.yaml`. However, it is not possible to associated `readOnly` and `writeOnly` to a property that relies on the use of `$ref`. For example, the following code is not valid.
```
properties:
   tagId:
      $ref: ../parameters/TagId.yaml
      readOnly: true
```

## Candidate solutions

- Solution 1: Keep the current approach where we have one schema (e.g. `Challenge.yaml`) that includes the property `challengeId` referenced with `$ref: ChallengeId.yaml`. The backend just ignores this property if provided as input to a POST request. The example provided in the page `/api/v1/ui` could be a bit confusing because they include `challengeId` as a possible parameter for the input, while the backend actually ignore this value.
  - A possible partial workaround is to find a way to have more control over the example provided, for example by specify different examples when a schema is used as input or output.

- Solution 2: Create different schema, for example `ChallengeCreateRequest` following the approach adopted by Nextflow Tower (see their [OpenAPI spec](https://tower.nf/openapi/nextflow-tower-api-latest.yml), search for "TraceCreateRequest").

I may be convinced to adopt Solution 2 because it provides more flexibility and would make our documentation more user-friendly. Because the solution adopted would be used to improve our other APIs that follow the same development model, I'm looking forward to hearing your thoughts @vpchung @thomasyu888 .

**Comment by thomasyu888** [comment]
Thanks @tschaffter for the details.  It's a bit unfortunate that we run into those issues when using `readOnly` and `writeOnly` as I think that is probably the most pretty solution.  That being said,  I am inclined to support "solution 2":

* Even though it may not adhere to DRY completely, I agree that this would provide us with more flexibility.  We could try to use `allOf` where we can to reduce the number of duplicated information: [example](https://github.com/OAI/OpenAPI-Specification/issues/425#issuecomment-212106574))
* This solution will most likely cause us the least trouble `openapi-generator` not supporting `readOnly`/`writeOnly`.  Although it may be worth it to open tickets to `openapi-generator` for them to to fully support those fields.

**Comment by tschaffter** [comment]
Sounds good! Pending @vpchung input.

> We could try to use allOf where we can to reduce the number of duplicated information: example)

I've seen this solution in the past. I've given it a try but I observed that the code generated by the generator was more obscure. I try to limit the use of `allOf` and `oneOf` whenever possible when using the `openapi-generator` until the generator handles these cases more elegantly.

**Comment by tschaffter** [comment]
I'm working on implementing Solution 2 (different schema for POST body request and return response) for the NLP Sandbox Data Node (see above ticket). I'm using the implementation of Tower NF as the main source of inspiration (link to their openapi.yaml posted above). I'll come back to this ticket once I have completed the task to share my findings.

**Comment by tschaffter** [comment]
It seems that OpenAPI 3.1 will enable the use of `readOnly` with `$ref` sibling ([source](https://stackoverflow.com/a/51402417)).

This is an improvement in itself. This however does not solve the issue of openapi-generator generating faulty examples of body requests that include `readOnly` properties, making example requests in `/api/v1/ui` fail, which can confuse the user/developer.
