### ISSUE TITLE
POST request should return 400 Bad Request when request body is ill formatted, 422 when input values are invalid

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc-schemas#51]
Invalid POST request should return 403 Forbidden instead of 404 ([reference](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1)).

For example, the POST challenge controller returns 404 if a tag submitted is not found. Returning 403 Forbidden seems a more descriptive response.

**Comment by tschaffter** [comment]
Actually either `400 Bad Request` or `422 Unprocessable Entity`

See https://stackoverflow.com/a/29912505

**Comment by vpchung** [comment]
In the original UML draft, the `403` and `422` status codes were suggested, where `403` is returned if the current user is not allowed to make changes to the objects and `422` is returned when the request can't be understood, either due to syntax or semantics.

Should I move forward with this approach?

**Comment by vpchung** [comment]
Quick clarification!

Title says to return 400 but description/comments say to return `403`/`422`. Should `400` also be returned?

**Comment by tschaffter** [comment]
Sorry for the confusion. Here are the proposed actions.

- [ ] Remove/comment out existing 403 response. The current issue is that we return `403 Unauthorized`, which is ambiguous because the [rfc2616 standard](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1)  define `401 Unauthorized`. Note that the name `401 Unauthorized` is ill defined in the standard because this error is about authentication and not authorization, which should be captured by `403 Forbidden`.
- [ ] Return `422 Unprocessable Entity` when the structure of the request body is correct but values specified are invalid (e.g. value not in list of possible enum value). See [400 vs 422 status codes](https://www.keycdn.com/support/422-unprocessable-entity#400-vs-422-status-codes).

**Comment by tschaffter** [comment]
@vpchung @thomasyu888  As I work on updating a service for the NLP Sandbox that implement the changes discussed in this ticket, I propose to only return `400 Bad Request` if the input request is not valid, independently of whether the request body is missing required properties (previously proposed to be handled as 422) or if properties values are invalid. In practice in a controller function, we convert the request body to an object based on a model. The model implementation automatically generated by `openapi-generator` takes care of the validation and throw an error if the input is invalid. Because it's difficult for us to identify whether we are truly in front of a 422 or 400 error, I propose to simplify and only return 400 when the input of a POST request is invalid.

**Comment by vpchung** [comment]
@tschaffter okay, that sounds reasonable to me!
