### ISSUE TITLE
Read OpenAPI Authentication and Authorization documentation

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc-schemas#64]
## Task

Read the page [Authentication and Authorization](https://swagger.io/docs/specification/authentication/) and related sections to better understand how we can use OpenAPI to implement local, OAuth 2.0 and API key-based authentication.

- [x] @vpchung read the doc
- [x] @tschaffter read the doc

**Comment by thomasyu888** [comment]
Ive done this for the synapse rest services: https://github.com/Sage-Bionetworks/synapse-rest-openapi/blob/main/openapi/openapi.yaml#L532-L537. Works out of the box when I create auto generated clients and use the Synapse Personal access token.

**Comment by tschaffter** [comment]
Done
