### ISSUE TITLE
Add DELETE operation to remove all entities of one type

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/rocc-schemas#67]
As I'm working through the client side, I find myself having to prune the database often (with `docker volume prune`). Rather than do that or deleting each entity individually until they're all removed, I suggest we add another `delete` operation, e.g.

<img width="807" alt="Screen Shot 2021-02-02 at 11 40 11 PM" src="https://user-images.githubusercontent.com/9377970/106713990-1079cf80-65b0-11eb-85ee-9cc561eb9349.png">

Obviously, this operation can be dangerous, so only a very small number of individuals should be granted authorization to perform this (maybe just us?).

@tschaffter thoughts?

**Comment by tschaffter** [comment]
Sounds good! We would also backup the DB in a production environment.
