### ISSUE TITLE
Update Challenge ID

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/rocc-schemas#85]
Challenge IDs are currently ObjectIDs.  For easier readability, they should be updated to challenge name in Github format (similar to Tag IDs and Organization IDs).

**Comment by tschaffter** [comment]
At the same time, I would suggest that we rename `Challlenge.challengeId` to `Challenge.id` and apply this convention to other properties named `<schema>.<schema>*`. See [GitHub API schemas](https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json).

**Comment by vpchung** [comment]
Sounds good. I actually prefer this, but I thought we wanted to follow the format of `*_id`.  Now, having `links` will be more useful for describing the responses!
